version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d url_shortener"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/url_shortener
      - JWT_SECRET=your_jwt_secret_here
      - PORT=3000
      - BASE_URL=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run generate && npm run migrate && npm run dev"

volumes:
  postgres_data:
